//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forms
    {
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Kraj { get; set; }
        public string Miejscowosc { get; set; }
        public System.DateTime Data { get; set; }
        public string Kod { get; set; }
        public byte[] Zalacznik { get; set; }
        public int FormID { get; set; }
    }
}
